### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /www/wwwroot/node_modules/svelte-hero-icons/heroicons/AcademicCap.json

### ISSUE THREAD

**Issue by wearefyi** [JustinVoitel/svelte-hero-icons#13]
Hey just installed this,

I'm getting this error: 
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /www/wwwroot/node_modules/svelte-hero-icons/heroicons/AcademicCap.json`

**Comment by babeard** [comment]
I'm also experiencing this. To give a little more context, it's happening when using `SvelteKit v1.0.0-next.202`. Versions 201 or prior work as expected. It may be related to kit upgrading Vite to 2.7.

**Comment by JustinVoitel** [comment]
@babeard Thank you for the help, seems like it's not that easy anymore to import JSON with vite 2.7.x. 
Anyway I added the config to the README!

With 3.1.0 you can now:
- Import the Icon component alongside the icon data, e.g:
```js
import {Icon, Annotation} from "svelte-hero-icons"
// importing the component via "svelte-hero-icons/Icon.svelte" is still possible

```


- use any valid html attribute on the Icon component (which will only be applied to the svg element) e.g.
```svelte
<Icon size="50" height="100" aria-hidden="true"> 
<!-- the height attribute overrides the value that would normally come from the size attribute-->
<!-- the ariaHidden attribute will be removed in a later major version, because you can now use the native aria-hidden attribute-->
```
- Better Typings for the Icon component

**Comment by wearefyi** [comment]
I am now getting the error:
`index.js:74 GET https://connectv3.wearefyi.dev/node_modules/svelte-hero-icons/heroicons/CurrencyYen.json?import net::ERR_HTTP2_SERVER_REFUSED_STREAM`

**Comment by JustinVoitel** [comment]
@wearefyi can you try `svelte-hero-icons@3.2.0-beta.0` ?
I've converted the icon source data from .json to .js files. Maybe it wasn't a good idea to use .json files in the first place, but I didn't know they would cause many problems in Vite/Kit ^^

**Comment by babeard** [comment]
@JustinVoitel I was getting some very strange SSR/Vite errors that I couldn't quite pinpoint to any one repo, but `svelte-hero-icons@3.2.0-beta.0` seems to have fixed it for me. Thanks!

--- 

On another note: A couple days ago I was playing with the idea of removing the need for `ssr: { noExternal: ['svelte-hero-icons'] }` altogether and converted all .json files to .js files like you  just did. The only blocker then was the `Unknown file extension ".svelte"` error emitted from vite 2.7's esm loader. The easiest way to resolve this is to remove the Icon.svelte export...

```diff
export {default as ZoomOut} from "./heroicons/ZoomOut.js"
-export {default as Icon} from "./Icon.svelte"
```

Of course then `import { Icon } from 'svelte-hero-icons';` wouldn't be a thing. 🤷‍♂️

**Comment by JustinVoitel** [comment]
@babeard 
I figured SvelteKit has a Problem having both imports, so in 4.0.1 I removed the `import Icon from "svelte-hero-icons/Icon.svelte"` since ultimately it takes more space. This is a Breaking but easily refactorable change! 

Now you don't need any configuration at all for this package (tested with npm & pnpm on mac). If there are still Problems please reopen or create a new Issue

**Comment by babeard** [comment]
Thanks!
