### ISSUE TITLE
run script, build:icons Problem!

### ISSUE THREAD

**Issue by Scouterdev** [JustinVoitel/svelte-hero-icons#14]
run script: 
 **"build:icons": "npm run clean && node --loader ts-node/esm build.ts",**

have message:
`> myproject@0.0.2 clean
> rm -rf src/lib/heroicons src/lib/index.js

'rm' is not recognized as an internal or external command,
operable program or batch file.
The terminal process "C:\Windows\System32\cmd.exe /d /c npm run build:icons" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.`

**Comment by JustinVoitel** [comment]
If you want to build the package using Windows, I recommend you to either use [WSL2](https://docs.microsoft.com/en-us/windows/wsl/) or a Docker container with a linux image.

Or you can fork the repo and adjust the commands to make it work with Windows
