### ISSUE TITLE
npmjs.org page for svelte-hero-icons doesn't link to this repo

### ISSUE THREAD

**Issue by ogrotten** [JustinVoitel/svelte-hero-icons#15]
There's no "Homepage" or "Repository" links in the sidebar, which makes getting here more difficult.

![image](https://user-images.githubusercontent.com/8119012/146438723-16dbe64e-e029-442f-99d6-df4533e854d5.png)

**Comment by JustinVoitel** [comment]
Thanks for the info :D
I forgot to transfer all the package.json stuff in a recent version when I moved the project to sveltekit ^^ will be added in 3.1.2
