### ISSUE TITLE
SvelteKit: node build fails with "Unknown file extension ".svelte""

### ISSUE THREAD

**Issue by MichaelBailly** [JustinVoitel/svelte-hero-icons#18]
Hello there,

thanks for your library, so convenient... 

I tried to build my SvelteKit app using the node adapter (https://kit.svelte.dev/docs#adapters-supported-environments-node-js) and it fails with the error:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for (...)/node_modules/svelte-hero-icons/Icon.svelte
```

When I add the magic ```noExternal: ["svelte-hero-icons"],``` in svelte.config.js it works. SMUI got the same issue and it seems that this can be overcome by putting additional fields in the package.json of your project:

https://github.com/hperrin/svelte-material-ui/issues/375

Maybe something worth considering?

**Comment by JustinVoitel** [comment]
@MichaelBailly
What versions of svelte-hero-icons and SvelteKit are you using? And how do you import the Icon component ? 

In version 4.0.1 you can now only import the Icon component like this: 'import {Icon} from "svelte-hero-icons"' which fixes the problem.

You are most probably using the old import Syntax

**Comment by benmccann** [comment]
I haven't tested, but it is very strange to me that this package is lacking `main` and `svelte` fields pointing to the entry point (i.e. `index.js`)

**Comment by JustinVoitel** [comment]
@benmccann since version 3.1.0 the `svelte` field is included. Is the `main` field needed aswell ? Will add that if it helps :)

**Comment by benmccann** [comment]
I think it's typically a good idea to have both `main` and `svelte` point to the same location. I think if you only had `svelte` it would work, but might generate a warning from Vite when used in SvelteKit
