### ISSUE TITLE
FingerPrint icon blocked by uBlock

### ISSUE THREAD

**Issue by mlhoutel** [JustinVoitel/svelte-hero-icons#19]
Hi,

First of all, thank you for the library.

I have encountered a problem when loading icons, probably due to a blocking of the uBlock extension on chrome:

The request to load the FingerPrint icon (`http://localhost:3000/node_modules/svelte-hero-icons/heroicons/FingerPrint.js`) is failing and results in a 500 error.

Is there a way to bypass this block when some icons are not availlable, or even disable them?

![image](https://user-images.githubusercontent.com/55429341/148458148-1fa61573-2f61-46a4-b463-bcec67ad635b.png)

**Config**
```
svelte-hero-icons 4.0.1
Chrome v96.0.4664.110
uBlock Origin: 1.40.4
```

**Comment by JustinVoitel** [comment]
Do the other icons work and only the fingerprint not ? Will have a look later

**Comment by mlhoutel** [comment]
Yes, only the FingerPrint icon is blocked.

For my current usage, I ended up using https://github.com/steeze-ui/icons that seems to work correctly.

It may be with the way the icons are loaded (only on call and not preloading all the icons?).

**Comment by 0gust1** [comment]
a coworker had this problem too.

It's the fault of uBlock which consider that a request containing the "fingerprint" word is a privacy-endangering tracking ressource. 

You can still whitelist the current website URL (localhost:3000) in uBlock.

**Comment by JustinVoitel** [comment]
Unfortunately I couldn't reproduce the error, but in 4.0.3 I renamed the import.
