### ISSUE TITLE
All icons loaded, one request each

### ISSUE THREAD

**Issue by andrejohansson** [JustinVoitel/svelte-hero-icons#21]
I'm using roughly 10-15 of the icons as can be seen in this picture:
![image](https://user-images.githubusercontent.com/2828428/152162805-079b7c12-08b2-479a-8b2d-34dc9ff1f126.png)

I'm importing them like this:
```ts
import { Icon, Home } from 'svelte-hero-icons';
```

And using them like this:
I'm importing them like this:
```ts
<Icon src={Home} solid class="flex-shrink-0 h-5 w-5" />
```

But for some reason it seems that **all** icons in the package gets loaded, using **one request per icon** which very much unnecessary work for something not being used.
![image](https://user-images.githubusercontent.com/2828428/152162771-8c7b3956-cedf-444f-afe0-6ca322b70e02.png)

Is this expected behaviour? Can I do something to prevent this?

I'm using 

```json
"svelte-hero-icons": "^4.0.3",
```

and using `optimizeDeps ` just causes the error mentioned in #18

**Comment by JustinVoitel** [comment]
Have you installed the package as dependency or devDependency ?

**Comment by andrejohansson** [comment]
As a devDependency!

**Comment by JustinVoitel** [comment]
@andrejohansson  Seems like something has changed on the SvelteKit or vite side where devDependencies aren't automatically optimized anymore. 

I have already fixed it in [@steeze-ui/icons](https://github.com/steeze-ui/icons) where now every Icon Source is bundled in 1 big index.js which fixes the import waterfalls and code splits in production builds.

When I have some time I'll change it in this package aswell!

**Comment by andrejohansson** [comment]
Much appreciated!

**Comment by JustinVoitel** [comment]
@andrejohansson now improved in 4.1.0
