### ISSUE TITLE
Error when rendering Icon.svelte with SvelteKit

### ISSUE THREAD

**Issue by eXodes** [JustinVoitel/svelte-hero-icons#23]
Hi, I am encountering an error with the SvelteKit with the latest source code.

```
[ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /home/worksmartly/Works/workmart/node_modules/svelte-hero-icons/Icon.svelte
```

I modified the `package.json` on my project `node_modules` package by reverting some part of the following commit https://github.com/JustinVoitel/svelte-hero-icons/commit/fdd7a6e9e3b268b1c2af7301aca08103b44187f7.

```
"files": [
    "*.svelte",
    "*.d.ts"
],
```

It was probably due to files that are allowed to be read from the package. I had to revert back to **v4.0.3** due to this issue. I hope this can be rectified the soonest.

**Comment by JustinVoitel** [comment]
I added it back in 4.1.1

@eXodes Please tell me if it works for you now!
