### ISSUE TITLE
[Question] import type IconSource

### ISSUE THREAD

**Issue by mazanec202** [JustinVoitel/svelte-hero-icons#24]
Hi (sorry for a noob question), 

I'm having issues importing the `IconSource` type, could you please lead me in the right direction?

I want to do this so I can use the type for having correctly typed props for a custom component.

Thank you!

**Comment by JustinVoitel** [comment]
Good catch! Types weren't exported correctly ^^

I've added them in version 4.1.3, so you can use it like this:
```svelte
<script lang="ts">
   import { Icon, Home, type IconSource } from "svelte-hero-icons"
   export let icon: IconSource = Home
</script>

<Icon src={icon} />
```

**Comment by mazanec202** [comment]
@JustinVoitel That was blazingly fast, thanks!
