### ISSUE TITLE
Wrong viewbox for solid icons

### ISSUE THREAD

**Issue by LeGmask** [JustinVoitel/svelte-hero-icons#25]
Solid icons should have a  0 0 20 20 viewbox instead of  0 0 24 24

**Comment by JustinVoitel** [comment]
According to the official sources from [heroicons](https://github.com/tailwindlabs/heroicons) the solid icons have a 0 0 20 20 viewbox!
Here an example: https://github.com/tailwindlabs/heroicons/blob/master/src/solid/eye.svg?short_path=3d01e9b

**Comment by LeGmask** [comment]
> According to the official sources from [heroicons](https://github.com/tailwindlabs/heroicons) the solid icons have a 0 0 20 20 viewbox! Here an example: [https://github.com/tailwindlabs/heroicons/blob/master/src/solid/eye.svg?short_path=3d01e9b](https://github.com/tailwindlabs/heroicons/blob/master/src/solid/eye.svg?short_path=3d01e9b&rgh-link-date=2022-08-16T09%3A30%3A16Z)

Yeah that's what I was thinking about, but my issue wasn't clear at all, should be fixed now
