### ISSUE TITLE
Deprecated package.json

### ISSUE THREAD

**Issue by DaniruKun** [JustinVoitel/svelte-hero-icons#32]
After upgrading to SvelteKit 2, I get this warning:

```
11:14:15 PM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-hero-icons@5.0.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

Should be easy to fix by following the steps here:
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by JustinVoitel** [comment]
fixed with version 5.1.0
