### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by SuperiorJT** [JustinVoitel/svelte-hero-icons#9]
I tried using this in an app of my own and am having issues getting it setup. I think it's a windows issue, but I don't really know. When running dev and navigating in the browser, I get this error.

```
[vite] Error when evaluating SSR module /src/routes/index.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Workspace\svelte-hero-icons\node_modules\svelte-hero-icons\index.js
require() of ES modules is not supported.
require() of C:\Workspace\svelte-hero-icons\node_modules\svelte-hero-icons\index.js from C:\Workspace\svelte-hero-icons\node_modules\vite\dist\node\chunks\dep-1be34a63.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Workspace\svelte-hero-icons\node_modules\svelte-hero-icons\package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (C:\Workspace\svelte-hero-icons\node_modules\vite\dist\node\chunks\dep-1be34a63.js:75033:17)
    at ssrImport (C:\Workspace\svelte-hero-icons\node_modules\vite\dist\node\chunks\dep-1be34a63.js:74975:20)
    at eval (/src/routes/index.svelte:7:37)
    at async instantiateModule (C:\Workspace\svelte-hero-icons\node_modules\vite\dist\node\chunks\dep-1be34a63.js:75018:9)
```

I've tried many different configurations on my project, so I finally decided to pull this to verify I didn't mess up the config. I understand that sveltekit is in beta, so it makes sense that there might be issues due to that.

If you have any ideas on what I could do to get this working, please let me know. Thanks!

**Comment by SuperiorJT** [comment]
Of course right after I post I get it working haha.
The fix for me to make it work on windows was to add this code to `svelte.config.js`:
```js
// ...
const config = {
    // ...
    kit: {
        // ...
        vite: {
            // ...
            ssr: {
                noExternal: ['svelte-hero-icons']
            }
        }
    }
}
```

I had tried this earlier today and ended up getting an invalid SSR component error. I'm not sure what I did in my config to fix that previous conflict, but it seems to be working for now. It might be a good idea to post this fix in the docs to make sure Windows users know what to do when they catch this error.

**Comment by JustinVoitel** [comment]
Are you using the latest versions on both svelte-hero-icons@3.0.0 and @sveltejs/kit@1.0.0-next.168 ? How does your import look like ?

**Comment by JustinVoitel** [comment]
@SuperiorJT it didn't show your answer when I was posting mine 😅 But yes good to know that you need extra config for windows systems since I only tested it on Unix ones! Do you know if this is vite or kit related ?

**Comment by JustinVoitel** [comment]
Okay thanks for the info! I added the workaround to the Readme 👍
